version: '3'
services:
  tman:
    build: 
      context: ./front
      args:
        BUILD_ENVIRONMENT: production
    ports:
      - "8081:80"
    depends_on:
      - phoenix
  phoenix:
    build: ./api
    ports:
      - "8080:4000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: